#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Gate build reachability for Host sources with explicit theorem/lemma commands."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
import argparse
import json
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
# Environment/.olean enumeration cannot discover the source module that was
# never built, and elaborating every Host source would turn this inventory into
# a second build (including the separately reserved liveness module). Keep the
# source scan, but make its declaration prefix deliberately conservative: once
# comments and strings are blanked, accept indentation, same-line attributes,
# Lean declaration modifiers, and other command-prefix tokens. A novel prefix
# can therefore create a false alarm, which fails closed, rather than hide an
# orphan. The claim established here is about explicit theorem/lemma commands;
# declarations generated by arbitrary macros require elaboration to enumerate.
THEOREM_DECL = re.compile(
    r"^[^\S\n]*(?:@\[[^\n]*\][^\S\n]*)*(?:[^\s]+[^\S\n]+)*?"
    r"(?:theorem|lemma)[^\S\n]+(«[^»\n]+»|[^\s:([{]+)",
    re.MULTILINE,
)
AXIOM_PIN = re.compile(
    r"#guard_msgs\s+in\s+#print\s+axioms\s+([A-Za-z_][A-Za-z0-9_'.]*)"
)
IMPORT_TOKEN = re.compile(
    r"^[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*$"
)

# RULED by Ben on 2026-08-01: dropped from the release claim. Its kernel
# reduction was measured at 6.0 GiB RSS / 1h51m CPU on 2026-07-31, which the
# release pipeline will not carry. It is NOT part of the maintained assurance
# case: nothing in the public claim surface asserts its theorems are built or
# axiom-checked. The source stays in the tree and stays visible in every
# generated inventory, so the exclusion is stated rather than silent. All other
# explicitly theorem/lemma-bearing Host sources are fail-closed.
RESERVED = {
    "Host.CanonicalL0Liveness": "dropped from the release claim (Ben, 2026-08-01); not part of the maintained assurance case",
}


class InventoryError(RuntimeError):
    """The inventory could not establish a trustworthy answer."""


@dataclass(frozen=True)
class InventoryRow:
    module: str
    discovered: bool
    assigned: str
    compiled: bool
    axiom_classified: bool
    orphaned: bool


@dataclass(frozen=True)
class Inventory:
    rows: tuple[InventoryRow, ...]
    errors: tuple[str, ...]

    @property
    def passed(self) -> bool:
        return not self.errors and not any(row.orphaned for row in self.rows)


def strip_lean_comments(text: str) -> str:
    """Blank nested Lean comments and strings while preserving line boundaries."""
    output: list[str] = []
    index = 0
    block_depth = 0
    in_string = False
    raw_string_closer: str | None = None
    in_quoted_identifier = False
    while index < len(text):
        if block_depth:
            if text.startswith("/-", index):
                block_depth += 1
                output.extend("  ")
                index += 2
            elif text.startswith("-/", index):
                block_depth -= 1
                output.extend("  ")
                index += 2
            else:
                output.append("\n" if text[index] == "\n" else " ")
                index += 1
        elif raw_string_closer is not None:
            if text.startswith(raw_string_closer, index):
                output.extend(" " * len(raw_string_closer))
                index += len(raw_string_closer)
                raw_string_closer = None
            else:
                output.append("\n" if text[index] == "\n" else " ")
                index += 1
        elif in_string:
            if text[index] == "\\":
                output.append(" ")
                index += 1
                if index < len(text):
                    output.append("\n" if text[index] == "\n" else " ")
                    index += 1
            elif text[index] == '"':
                in_string = False
                output.append(" ")
                index += 1
            else:
                output.append("\n" if text[index] == "\n" else " ")
                index += 1
        elif in_quoted_identifier:
            output.append(text[index])
            if text[index] == "»":
                in_quoted_identifier = False
            index += 1
        elif text[index] == "r":
            raw_start = re.match(r'r(#{0,})"', text[index:])
            if raw_start:
                marker = raw_start.group(1)
                output.extend(" " * len(raw_start.group(0)))
                index += len(raw_start.group(0))
                raw_string_closer = f'"{marker}'
            else:
                output.append(text[index])
                index += 1
        elif text[index] == "«":
            in_quoted_identifier = True
            output.append(text[index])
            index += 1
        elif text.startswith("/-", index):
            block_depth = 1
            output.extend("  ")
            index += 2
        elif text.startswith("--", index):
            newline = text.find("\n", index + 2)
            if newline == -1:
                output.extend(" " * (len(text) - index))
                break
            output.extend(" " * (newline - index))
            output.append("\n")
            index = newline + 1
        elif text[index] == '"':
            in_string = True
            output.append(" ")
            index += 1
        else:
            output.append(text[index])
            index += 1
    if block_depth:
        raise InventoryError("unterminated Lean block comment")
    if in_string:
        raise InventoryError("unterminated Lean string literal")
    if raw_string_closer is not None:
        raise InventoryError("unterminated Lean raw string literal")
    if in_quoted_identifier:
        raise InventoryError("unterminated Lean quoted identifier")
    return "".join(output)


def lean_sources(root: Path) -> dict[str, Path]:
    sources: dict[str, Path] = {}
    excluded = {".git", ".lake", "node_modules", "target"}
    for path in root.rglob("*.lean"):
        relative = path.relative_to(root)
        if relative.parts[0] in excluded:
            continue
        module = ".".join(relative.with_suffix("").parts)
        if module in sources:
            raise InventoryError(f"duplicate Lean source for {module}")
        sources[module] = path
    return sources


def parse_imports(path: Path) -> tuple[str, ...]:
    source = strip_lean_comments(path.read_text(encoding="utf-8"))
    imports: list[str] = []
    for line_number, line in enumerate(source.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped == "prelude":
            continue
        match = re.match(r"^\s*import(?:\s+(.+?))?\s*$", line)
        if not match:
            break
        tail = match.group(1)
        if not tail:
            raise InventoryError(f"empty import at {path}:{line_number}")
        modules = tail.split()
        invalid = [module for module in modules if not IMPORT_TOKEN.fullmatch(module)]
        if invalid:
            raise InventoryError(
                f"cannot parse import at {path}:{line_number}: {' '.join(invalid)}"
            )
        imports.extend(modules)
    return tuple(imports)


def import_closure(root_module: str, sources: dict[str, Path]) -> set[str]:
    if root_module not in sources:
        raise InventoryError(f"cannot resolve build-wire root {root_module}")
    closure: set[str] = set()
    queue = [root_module]
    local_roots = {module.split(".", 1)[0] for module in sources}
    while queue:
        module = queue.pop()
        if module in closure:
            continue
        path = sources.get(module)
        if path is None:
            if module.split(".", 1)[0] in local_roots:
                raise InventoryError(f"cannot resolve local import {module}")
            continue
        closure.add(module)
        queue.extend(parse_imports(path))
    return closure


def is_axiom_classified(
    module_path: Path, declarations: tuple[str, ...], all_pins: set[str]
) -> bool:
    source = module_path.read_text(encoding="utf-8")
    if AXIOM_PIN.search(strip_lean_comments(source)):
        return True
    return any(
        pin == declaration or pin.endswith(f".{declaration}")
        for declaration in declarations
        for pin in all_pins
    )


def evaluate(root: Path = ROOT) -> Inventory:
    errors: list[str] = []
    try:
        sources = lean_sources(root)
        assigned = import_closure("Test.Axioms", sources)
    except (InventoryError, OSError) as exc:
        return Inventory((), (str(exc),))

    host_dir = root / "Host"
    axiom_sources = [root / "Test" / "Axioms.lean", *sorted(host_dir.glob("*.lean"))]
    all_pins: set[str] = set()
    try:
        for path in axiom_sources:
            all_pins.update(AXIOM_PIN.findall(strip_lean_comments(path.read_text(encoding="utf-8"))))
    except (InventoryError, OSError) as exc:
        return Inventory((), (str(exc),))

    rows: list[InventoryRow] = []
    for path in sorted(host_dir.glob("*.lean")):
        try:
            source = strip_lean_comments(path.read_text(encoding="utf-8"))
        except (InventoryError, OSError) as exc:
            errors.append(f"{path}: {exc}")
            continue
        declarations = tuple(THEOREM_DECL.findall(source))
        if not declarations:
            continue
        module = f"Host.{path.stem}"
        reservation = RESERVED.get(module)
        assignment = "axiom_check" if module in assigned else (reservation or "UNASSIGNED")
        olean = root / ".lake" / "build" / "lib" / "lean" / Path(*module.split("."))
        # A stray artifact in a warm .lake is not release reachability. The
        # module must be in the source-derived axiom_check closure as well as
        # have the artifact produced/validated by the immediately preceding
        # default build.
        compiled = module in assigned and olean.with_suffix(".olean").is_file()
        orphaned = reservation is None and (module not in assigned or not compiled)
        rows.append(
            InventoryRow(
                module=module,
                discovered=True,
                assigned=assignment,
                compiled=compiled,
                axiom_classified=is_axiom_classified(path, declarations, all_pins),
                orphaned=orphaned,
            )
        )
    return Inventory(tuple(rows), tuple(errors))


def print_table(inventory: Inventory) -> None:
    # axiom_classified is diagnostic only. Source spelling and namespaces make
    # the repo-wide suffix heuristic unsuitable as a reachability condition.
    print("module\tdiscovered\tassigned\tcompiled\taxiom-classified(non-gating)\torphaned")
    for row in inventory.rows:
        print(
            f"{row.module}\tyes\t{row.assigned}\t"
            f"{'yes' if row.compiled else 'no'}\t"
            f"{'yes' if row.axiom_classified else 'no'}\t"
            f"{'yes' if row.orphaned else 'no'}"
        )
    print(
        "summary\t"
        f"discovered={len(inventory.rows)}\t"
        f"assigned={sum(row.assigned == 'axiom_check' for row in inventory.rows)}\t"
        f"compiled={sum(row.compiled for row in inventory.rows)}\t"
        f"axiom-classified(non-gating)={sum(row.axiom_classified for row in inventory.rows)}\t"
        f"orphaned={sum(row.orphaned for row in inventory.rows)}\t"
        f"reserved={sum(row.module in RESERVED for row in inventory.rows)}"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    inventory = evaluate(args.root.resolve())
    if args.json:
        print(json.dumps({"rows": [asdict(row) for row in inventory.rows], "errors": inventory.errors}, indent=2))
    else:
        print_table(inventory)
    for error in inventory.errors:
        print(f"ORPHAN PROOF MODULE: inventory error: {error}", file=sys.stderr)
    for row in inventory.rows:
        if row.orphaned:
            print(
                f"ORPHAN PROOF MODULE: {row.module} "
                f"assigned={row.assigned} compiled={'yes' if row.compiled else 'no'}",
                file=sys.stderr,
            )
    return 0 if inventory.passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
